apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollout-bluegreen.yaml
- service-bluegreen-active.yaml
- service-bluegreen-preview.yaml
- ingress-bluegreen.yaml
- ingress-bluegreen-preview.yaml

images:
- name: bernardolankheet/lab-blue-green
  newTag: green